### ISSUE TITLE
Can‘t find camera

### ISSUE THREAD

**Issue by zoumaguanxin** [transcendrobotics/zed_cpu_ros#15]
I have connected the zed with computer, and the zed_ros_wrapper provided by stereolabs can work. But this package can't find camera. why did the situation happen?

**Comment by JasonQueen94** [comment]
Change your device id parameter within the zed_cpu_ros.launch file

**Comment by zoumaguanxin** [comment]
Thanks. It works.

**Comment by zoumaguanxin** [comment]
use `lsusb` to find the device id
