### ISSUE TITLE
Found bugs when trying to use stereo_image_proc

### ISSUE THREAD

**Issue by prarinya-s** [transcendrobotics/zed_cpu_ros#2]
Thank you for the great work. It do help us to work on ZED without GPU.
I have tried to use your zed_cpu_ros with the stereo_image_proc ROS package. I found several bugs as follow.

line 232-237
```
switch (resolution) {
		case 0: reso_str = "2K";
		case 1: reso_str = "FHD";
		case 2: reso_str = "HD";
		case 3: reso_str = "VGA";
}
```
reso_str always select VGA resolution. You should add the _break_ here.

line 288-289
```
left_info.R.fill(0.0);
right_info.R.fill(0.0);
```
I think you can compute R from RZ and RX in zed config file, or it should be at least identity matrix

Sincerely yours,
Prarinya

**Comment by willdzeng** [comment]
Hi Prarinya,

For this part, I referenced the official [zed_ros_warpper](https://github.com/stereolabs/zed-ros-wrapper/blob/master/src/zed_wrapper_nodelet.cpp#L365). Looks like it's wrong.

So the Rectification matrix should be
```
[Rx  0   0 ]
[0   1   0 ]
[0   0   Rz]
```

**Comment by willdzeng** [comment]
But I noticed the value giving in my zed config is
```
RX_2K=0.00388714
RX_FHD=0.00388714
RX_HD=0.00388714
RX_VGA=0.00388714
RZ_2K=-0.00139603
RZ_FHD=-0.00139603
RZ_HD=-0.00139603
RZ_VGA=-0.00139603
```
I am not sure this RX and RZ is indicating which value in the 3x3 Rectification Matrix, Do you have any idea?

**Comment by prarinya-s** [comment]
I think RX and RZ should refer to the extrinsic rotation matrix. From the look, I guess they gave the rotation angles in radian \theta_x and \theta_z.

From wikipedia https://en.wikipedia.org/wiki/Rotation_matrix#In_three_dimensions , rotation matrix can be calculated by finding rotation in every axes. So you got R_x(\theta_x), R_z(\theta_z), R_y=I. The final rotation matrix R = R_z(\theta_z) x I x R_x(\theta_x)

So, I did calculated the above equations. The resultant rotation matrix R look similar to the rotation matrix I got from other stereo camera (very close to identity matrix).

I am not sure if I was wrong about this. Please check on this if able. At the moment, I set the R to identity matrix, and _stereo_image_proc_  package work very well with this setting.

**Comment by willdzeng** [comment]
Cool, The recent commits also set the R matrix as identity, but I again failed to do the image_proc for some reason, how did you do that?

Also, I think it's better to do a calibration yourself using ROS's stero_proc package. I got a launch file that can do this which you might want to check out.

**Comment by willdzeng** [comment]
Here I found an interesting explanation,
https://github.com/stereolabs/zed-ros-wrapper/issues/39
The rotation (in rotation vector form, convertible into matrix with Rodrigues formula) are the following:
```
Rx = RX (in rad),
Ry = CV,
Rz = RZ.
```

**Comment by prarinya-s** [comment]
Thanks for the info on rotation matrix.

For the calibration, I used the ZED calibration tool in the ZED SDK. It gave a better calibration for me. However, they seem to record it in float32 not float64. So the precision are very limited. How about your case ?

By the way, it works with your roslaunch like a charm. Thank you for you great work.

**Comment by willdzeng** [comment]
the ZED calibration works better for me also.

Thank you for your compliment!

**Comment by willdzeng** [comment]
Hi @prarinya-s 
Can you help me check if the new commits are right in terms of the rectification?
I don't have the camera with me, so I can't really check if it works or not.
https://github.com/willdzeng/zed_cpu_ros/commit/09ffa6eb4c43f1ea30b9526ac16ec16baeda6f2c
Thanks.
