### ISSUE TITLE
Library Usage

### ISSUE THREAD

**Issue by WeeFella** [transcendrobotics/zed_cpu_ros#20]
I've installed the library on my robot. When I run the launch file, I get "Success, found camera". How can I use this library now to capture images and save them?

**Comment by MajdWardeh** [comment]
one way to do so by rqt_image_view to run it, please type:
rosrun rqt_image_view rqt_image_view

**Comment by willdzeng** [comment]
you can use http://wiki.ros.org/image_view to capture and save images
