### ISSUE TITLE
Launch file logs webcam instead of Zed

### ISSUE THREAD

**Issue by AkshayHinduja** [transcendrobotics/zed_cpu_ros#5]
Hi, the node for some reason opens up my webcam instead of the zed camera. The zed ros wrapper works fine though. Any idea as to why this is happening?

**Comment by willdzeng** [comment]
https://github.com/willdzeng/zed_cpu_ros/blob/master/src/zed_cpu_ros.cpp#L36

Here it's assuming the 0 camera is the zed, maybe change this to 1, see if that works

**Comment by AkshayHinduja** [comment]
Yes, that worked. Thank you!

I also wanted to ask if you knew why it is difficult to use stereo_image_proc on the higher resolutions? 

Also, why is it that the zed_ros_wrappers raw images dont create a pointcloud in stereo_image_proc?

**Comment by willdzeng** [comment]
point cloud requires depth image, Zed need GPU to calculate depth. Raw image only has RGB.
