### ISSUE TITLE
Change frame rate

### ISSUE THREAD

**Issue by yuchango** [transcendrobotics/zed_cpu_ros#6]
Hi.

I am trying to change the frame rate, but I always get the error
VIDIOC_QUERYMENU: Invalid argument

Is there any restriction about going over 30 fps even for WVGA?
Because I had no problems lowering the fps, but I cannot go over 30.

Thanks!

**Comment by willdzeng** [comment]
Are you connected to a USB 3.0?

**Comment by yuchango** [comment]
Thanks for your quick reply.

I was completely fooled by blue USB ports (I thought they were 3.0...) Sorry for the stupid error.
I tried in the USB 3.0 port, but now I got:

libv4l2: error turning on stream: Input/output error
VIDIOC_STREAMON: Input/output error
VIDIOC_QBUF: No such device

Any idea of the problem? 
Could it be that I am trying to use it in ubuntu 14.04?
I'll also try to debug it. Thanks again!

**Comment by willdzeng** [comment]
Have you found what's causing that?

**Comment by willdzeng** [comment]
usually if you can't find device, that means either the device id is wrong, or your zed is not properly connected.
Try to use the default zed tool show the image first
```
/usr/local/zed/tools/ZED\ Explorer 
```
See if you can get the image, if not, check your connection.
If you do see image with the explorer, try use
```
ls /dev/video*
```
and find which id it is.

**Comment by willdzeng** [comment]
Let me know if you still have the issue.

**Comment by saimanoj18** [comment]
Hi,

I am working on Ubuntu 16.04 with ZED and I am not able to change the frame rate. I cannot lower nor increase the frame rate.

I am using HD resolution 1280 x 720.

I have checked with ZED Explorer and there I can achieve 60 frames per second but while using zed_cpu_ros, I am not able to change the frame rate.

Could you please suggest what can I do to achieve 60 FPR with HD ?

Thanks!


**Here is the ROS Terminal Output!**
`---------------------------------------------------------------
sai@dell:~/sai_workspace/catkin_ws$ roslaunch zed_cpu_ros zed_cpu_ros.launch 
... logging to /home/sai/.ros/log/7a3ef7ae-535e-11e8-b206-d4258b95a812/roslaunch-dell-30440.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://dell:35377/

SUMMARY
========

PARAMETERS
 * /camera/zed_cpu_ros_node/config_file_location: /home/sai/sai_wor...
 * /camera/zed_cpu_ros_node/device_id: 1
 * /camera/zed_cpu_ros_node/encoding: bgr8
 * /camera/zed_cpu_ros_node/frame_rate: 60
 * /camera/zed_cpu_ros_node/left_frame_id: left_frame
 * /camera/zed_cpu_ros_node/resolution: 2
 * /camera/zed_cpu_ros_node/right_frame_id: right_frame
 * /camera/zed_cpu_ros_node/show_image: False
 * /camera/zed_cpu_ros_node/use_zed_config: True
 * /rosdistro: kinetic
 * /rosversion: 1.12.13

NODES
  /camera/
    zed_cpu_ros_node (zed_cpu_ros/zed_cpu_ros)

ROS_MASTER_URI=http://localhost:11311

process[camera/zed_cpu_ros_node-1]:started with pid [30459]
[ INFO] [1525853580.416143181]: Try to initialize the camera
[ INFO] [1525853580.644543860]: Stereo Camera Set Resolution 2, width 2560.000000, height 720.000000
[ INFO] [1525853580.644685000]: Initialized the camera
[ INFO] [1525853580.735239721]: Try load camera calibration files
[ INFO] [1525853580.735273936]: Loading from zed calibration files
[ INFO] [1525853580.735902671]: Got camera calibration files
[ INFO] [1525853580.749854479]: Success, found camera
 ---------------------------------------------------------------

**Here is the ROSTOPIC HZ**

sai@dell:~$ rostopic hz /camera/left/image_raw/
subscribed to [/camera/left/image_raw]
average rate: 29.969
	min: 0.015s max: 0.070s std dev: 0.00858s window: 28
average rate: 29.944
	min: 0.015s max: 0.070s std dev: 0.00623s window: 58
average rate: 29.702
	min: 0.015s max: 0.070s std dev: 0.00582s window: 86`

**Comment by willdzeng** [comment]
Did you connect your zed to USB3.0? can you try change to lower resolution and see if the frequency change at all?
