### ISSUE TITLE
[camera] does not match name warning

### ISSUE THREAD

**Issue by GuidoBartoli** [transcendrobotics/zed_cpu_ros#7]
Hi,
I followed all the steps in the **Usage** section, but when I run `roslaunch zed_cpu_ros zed_cpu_ros.launch`, I receive the following error: `[camera] does not match name narrow_stereo/left` (similar for right camera, too).
I saw that inside `zed_cpu_ros.cpp` there is a line `info_manager.setCameraName("zed/left")`, so I renamed `narrow_stereo` to `zed` in both yaml files, but now the error is `... does not match name zed/left`, so this did not resolve the issue.

Do you know if I'm doing something wrong here?

Thanks in advance

**Comment by willdzeng** [comment]
Have you tried to load zed's config?
```
info_manager.setCameraName("zed/left");
```
is only called when zed config is not loaded, and it shouldn't affect anything.

**Comment by willdzeng** [comment]
This should be fixed by 
https://github.com/willdzeng/zed_cpu_ros/pull/13

Thanks for reporting.

**Comment by GuidoBartoli** [comment]
Yes, now it works, thanks!
